services:
  - type: web
    name: devtrack-api
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./backend/DevTrack.API/Dockerfile
    dockerContext: ./backend/DevTrack.API
    healthCheckPath: /health
    autoDeployTrigger: commit

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

      - key: ConnectionStrings__DefaultConnection
        sync: false

      - key: Jwt__Key
        generateValue: true

      - key: Jwt__Issuer
        value: DevTrack.API

      - key: Jwt__Audience
        value: DevTrack.Client

      - key: Jwt__ExpireMinutes
        value: "60"

      - key: FrontendUrl
        sync: false
